### PR TITLE
ops #109089: Update ssld legend status colors

### PR DESCRIPTION
**Pull request by inefoss**
## Checklist
- [x] I have run linter.
- [ ] I added some tests. (to be defined further) [optional]
- [ ] I have updated [the wiki.](https://github.com/equinor/echo-maps/wiki) [optional]

## Primary description
- Update ssld legend status colors
- Rearrange them according to the design

Ref [AB#109089](https://dev.azure.com/EquinorASA/13429306-9600-4820-ac5c-3e7d26fa3cb9/_workitems/edit/109089)

## Screenshots
image

### CODE REVIEW

**Comment by olsoybakk** [comment]
Why not use the same method as I used in WBOLegend? It creates the legend automatically based on data from Robim.

**Comment by inefoss** [comment]
> Why not use the same method as I used in WBOLegend? It creates the legend automatically based on data from Robim.

That sounds better than how it is now, I will check it out

**Comment by inefoss** [comment]
Could not be used out of the box since filters are handled differently on SSLD in terms of filtering. But I added the filters back to the collection, and then I can look at combining them when looking at the other filter bugs so that we don't have two places to store the filters.

**Review by olsoybakk — APPROVED** [review]
👏🏻

**Pull request merged**
