### PR TITLE
ops #58753: endOfLine auto

### PR DESCRIPTION
**Pull request by olsoybakk**
## What's new
Set endOfLine to auto to disable annoying warnings

### CODE REVIEW

**Comment by ErlendAHall** [comment]
Make sure you have set git to auto convert line endings to `lf` once files are committed.

`git config core.autocrlf true`
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=windows

**Comment by olsoybakk** [comment]
@ErlendAHall `git config --get core.autocrlf` returns true

**Comment by olsoybakk** [comment]
image

**Review by ErlendAHall — APPROVED** [review]

**Comment by ErlendAHall** [comment]
Approved. Let's try it out. We just don't want to have crlf's committed.

**Pull request merged**
